services:
  - type: web
    name: ethnos-wallet-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
    plan: free
    region: oregon